### ISSUE TITLE
Access to Application settings

### ISSUE THREAD

**Issue by joerussbowman** [mrjoes/tornadio2#11]
It would be helpful to get access to the core application. For example then items like get_secure_cookie could be set up as you'd have access to the settings. ie: cookie_secret

The context of the request is that I'm working to try and add tornadio2 support to AsyncMongo-Sessions. My library uses set_secure_cookie and get_secure_cookie to manage the tokens.

**Comment by mrjoes** [comment]
Unfortunately, you can not rely on methods present in the Tornado RequestHandler, because it won't be always available in your tornadio application.

Instead, handle all your authentication logic in on_open - it accepts object which contains all cookies, query string parameters etc. Unfortunately, it was not designed to allow setting cookie - completely unexpected behavior from socket.io server.

So, if you need get_secure_cookie, you have few options:
1. Check how get_secure_cookie works and use it against cookies collection found in ConnectionInfo object which is passed to on_open()
2. Wait for me to do it (will take some time, though)

On a side note - with current implementation of TornadIO2 you can expect running RequestHandler during on_open() and access it through self.session.handler:

```
def on_open(self, info):
    # print cookie
    print info.get_cookie('cookie')

    # hackish way to get to cookie
    print self.session.handler.get_secure_cookie('cookie')
```

**Comment by joerussbowman** [comment]
I was able to get at what I wanted, which was the application settings this way. I added the settings from the main app when I instantiate the socket server app. This gives me access to the cookie_secret which is used to decode the secure cookies. This seemed a bit more elegant. This may be more of a howto than an actual issue, since it's really based on how you set things up. I'll close the issue.

if **name** == "**main**":
    tornado.options.parse_command_line()
    app = Application()
    sock_app = tornado.web.Application(
        ChatRouter.urls,
        flash_policy_port = 843,
        flash_policy_file = op.join(ROOT, 'flashpolicy.xml'),
        socket_io_port = 8002,
        **app.settings
    )

**Comment by prongs** [comment]
@joerussbowman : I don't understand what you did. Can you elaborate? The following is my code. What do I do so that I can use `self.settings.get('db')` inside my subclass of `SocketConnection`

```
class Application(tornado.web.Application):
    def __init__(self):
        mappings = handlers.mappings + [
            (r"/([^/]+)?", MainHandler)
        ]
        tornado_settings = dict(
            template_path=os.path.join(os.path.dirname(__file__), "templates"),
            static_path=os.path.join(os.path.dirname(__file__), "static"),
            debug=True,
            cookie_secret="smthing",
            login_url="/auth/login",
            xsrf_cookies=True,
            facebook_app_id=options.facebook_app_id,
            facebook_secret=options.facebook_secret,
            ui_modules={"Post": PostModule},
            autoescape=None,
            db=db,
            socket_io_port=8888
        )
        tornado.web.Application.__init__(self, mappings, **tornado_settings)


def main():
    tornadio2.SocketServer(Application())


if __name__ == "__main__":
    main()
```

**Comment by joerussbowman** [comment]
The project I wrote that for is long gone, looking at my code it appears what I did was 

build the main website application, it's variable name was app

Then I built the sockjs application

When I instantiated it, as a part of it's settings I copied the website application settings in it using the **app.settings pointer.

Obviously for my app (and is a general good practice) app settings never changed, since what I plugged in the sockjs app was just a copy, not a pointer. 

If that doesn't make sense, I'd suggest learning a bit more about kwargs in python. This stackoverflow link is a good start, you can also just google "python kwargs".

http://stackoverflow.com/questions/1769403/understanding-kwargs-in-python
