### ISSUE TITLE
Multiplexed connection does not receive query string arguments

### ISSUE THREAD

**Issue by Alerion** [mrjoes/tornadio2#13]
For example:

```
class UserConnection(tornadio2.conn.SocketConnection):

    def on_open(self, info):
        print  info.arguments  # {}

class RouterConnection(tornadio2.conn.SocketConnection):
    __endpoints__ = {
        '/user': UserConnection
    }
```

Connection:

```
var s = new io.connect('http://' + window.location.hostname + ':8002/user?sid=100500', {
    rememberTransport: false
});
```

Did I miss something? 
I fount one way: save `request.arguments` in `tornadio2.session.Session.__init__` and add them to `ConnectionInfo` in `tornadio2.session.Session.connect_endpoint` method.

**Comment by mrjoes** [comment]
Described here: http://tornadio2.readthedocs.org/en/latest/bugs/ and there's open ticket here: https://github.com/LearnBoost/socket.io-client/issues/331

There's no ETA when socket.io guys will fix it :-\

**Comment by Alerion** [comment]
Sorry, have read this section, but totally forgot about this. Thx for answer.
