### ISSUE TITLE
The best way to implement authentication

### ISSUE THREAD

**Issue by Alerion** [mrjoes/tornadio2#18]
Maybe you thought about authentication or have made it in projects. I'd be grateful for some hints about authentication in Tornadio2.

The most easy way I see is to check request in `tornadio2.router.HandshakeHandler.get` and prevent session create for inappropriate users. So for any try to send messages not authenticated user will receive `HTTPError(401, 'Invalid session')`.

**Comment by mrjoes** [comment]
Implement your authentication logic in `on_open`. If you return `False`, connection will be closed.

You have access access to query string parameters and cookies in `on_open` to perform any actions you need.

**Comment by Alerion** [comment]
I missed this. It will work as I mean, but without changing source code.
Thank you.
