### ISSUE TITLE
SessionContainer.remove does not remove session from self._queue

### ISSUE THREAD

**Issue by Alerion** [mrjoes/tornadio2#20]
Way to reproduce:
1. add session#1
2. remove session#1
3. create session#2 with session#1.session_id
4. call SessionContainer.expire, our new session is removed.

I understand that it is not common situation, but in my opinion `SessionContainer.remove` should totally remove remove session.

**Comment by Alerion** [comment]
By the way maybe you can give one more hint how save session after page reload? :)  

I've made saving session_id in cookie and passing it to a little changed `TornadioRouter.create_session` with:

```
var s = new io.connect(HOST+'user', {
    rememberTransport: false,
    query: 'session_id=' + getCookie(SESSION_COOKIE_NAME)
});
```

In `TornadioRouter.create_session` I remove old session with passed `session_id` and create new one with same `session_id`. So now I can save some session data in Redis or other DB. 

It works without errors, but I am afraid to get some problems after such changed in tornadio.

**Comment by mrjoes** [comment]
Unfortunately, you can't reuse session ID.

Also, way priority queues work, you can't remove element from the queue at will. You have to "pop" it from the queue after all preceding items were popped.

As for the persistance - do not rely on the session id generated by tornadio2. Instead, associate user with your own random value.

For example:
`var s = new io.connect(HOST+'user'+'?sid=' + getCookie(SESSION_COOKIE_NAME) ... );`

On server side check if sid parameter is empty (in on_open). If it is empty - generate new random value and send to the client (good to use event for that).

When client will receive this message, store session id in the cookie.

So, you don't hack around session handling of socket.io and tornadio2 and still achieve desired functionality.

**Comment by Alerion** [comment]
What about such way removing from `_queue`:

```
self._queue.remove(session)
heapq.heapify(self._queue)
```

**Comment by mrjoes** [comment]
It is very time consuming - it has complexity of O(2n). So, no, this won't work, as queue management should be as fast as possible.
