### ISSUE TITLE
Issues with Chrome and Opera

### ISSUE THREAD

**Issue by 23doors** [mrjoes/tornadio2#21]
Just tested examples that are in the source.
This is common for all examples, but I used ackping to post these logs.

My OS is OSX lion (if that's relevant).

**Opera 11.60**: websockets wont work, nor will flashsocket

DEBUG:root:<<< 1::
INFO:root:200 GET /socket.io/1/?t=1327023775575 (127.0.0.1) 0.92ms
WARNING:root:404 GET /socket.io/static/flashsocket/WebSocketMain.swf (127.0.0.1) 0.66ms
DEBUG:root:Initializing xhr-polling transport.

And goes on with xhr-polling.

**Chrome 16.0.912.75**: websockets wont work, flashsocket is not even tested

INFO:root:304 GET / (127.0.0.1) 18.03ms
INFO:root:304 GET /socket.io.js (127.0.0.1) 33.66ms
DEBUG:root:<<< 1::
INFO:root:200 GET /socket.io/1/?t=1327024036562 (127.0.0.1) 2.12ms
WARNING:root:404 GET /favicon.ico (127.0.0.1) 0.60ms
DEBUG:root:Initializing websocket handler.
DEBUG:root:Initializing xhr-polling transport.
INFO:root:200 GET /socket.io/1/xhr-polling/c828c0c6e97d475bcc0f02ffbd14c630?t=1327024046839 (127.0.0.1) 1.34ms
DEBUG:root:Initializing xhr-polling transport.

Tests run on localhost, port 80, no cross domain content, root privileges.

Safari tested: works - immediately goes to websockets.
Firefox 9 (with websockets enabled) - works as well, havent tried disabled websockets (which is by default).

I also tried node socket.io examples - these work normally with Chrome (websockets transport as well).

Here is what is happening on client-side with Chrome and Firebug.
GET http://localhost/socket.io/1/?t=1327024253984 returns 200 OK:
74cd3f19e29a2d86035ab15f0bfa6dea:12:25:websocket,flashsocket,xhr-polling,jsonp-polling,htmlfile

Then:
GET ws://localhost/socket.io/1/websocket/74cd3f19e29a2d86035ab15f0bfa6dea HTTP/1.1
Origin: http://localhost
Connection: Upgrade
Host: localhost
Sec-WebSocket-Key: hNDhwJlWrIbONI27pRBX5Q==
Upgrade: websocket
Sec-WebSocket-Version: 13

No response.
No error at all as well.

**Comment by 23doors** [comment]
UPDATE: I believe this is related to https://github.com/facebook/tornado/issues/423

Just tested with tornado from git repo - works flawlessly. So next release of tornado will make it work again. 

There isnt probably much you can do on your side although I haven't checked how it is fixed. Possibly this is something you should note somewhere? These latest changes broke almost all of python websockets servers I tested (gevent-websockets even though not tornado related, also is broken).

**Comment by mrjoes** [comment]
Hi,

Yes, it is related to the tornado bug 423 - current stable tornado version does not support latest hybi draft (or rfc now).

Opera does not work for cross-domain deployments, that's known issue.

For sockjs-tornado, I manually implemented new RFC and it works with older tornado versions. Might do this for tornadio2 as well.
