### ISSUE TITLE
Scalability (sessions)

### ISSUE THREAD

**Issue by kingel** [mrjoes/tornadio2#22]
I'm looking into ways of scaling our tornadio2 setup. At this moment our stack is like

stud > haproxy > nginx (static) / tornadio2 (websockets/longpolling) 

and this works wonderful, but adding another tornadio2 server to the setup and use haproxy to loadbalance it I get "HTTPError: HTTP 401: Unauthorized (Invalid Session)" which make sense, because one instance doesn't know about the sessions from the other instance.

In the documentation (http://tornadio2.readthedocs.org/en/latest/deployment/#scalability) I read about a memcached/redis backed session store, which was the first thing i was thinking about, is there any example around how to implement this in tornadio2? I found some examples for tornado but they look really different from the way tornado2 works.

The other option, using a transport mechanism to communicate between servers sounds interesting to because we already use rabbitmq to get the client statements to workers and the results back. Any tips or examples how to start with this?

**Comment by mrjoes** [comment]
Hi,

You have to enable sticky sessions in your haproxy configuration. With haproxy you can use either cookie, source IP or both to decide which server to use.

For example::

 listen http_proxy :80
        mode http
        cookie SERVERID
        balance source
        server web1 192.168.1.1 cookie server01
        server web2 192.168.1.2 cookie server02
        server web3 192.168.1.3 cookie server03

This will tell haproxy to attempt to set balancing cookie and if it is absent (cookies are disabled or something else happened), it will use IP address to forward client to proper host.

As for the transports - it all depends on your application. For example, if you have IRC-like chat with rooms, you have to synchronize messages between server instances. That's all what I meant in this section. Tornadio2 does not provide any cross-server synchronization features.
