### ISSUE TITLE
Access-Control-Allow-Credentials header case

### ISSUE THREAD

**Issue by kulik0v** [mrjoes/tornadio2#34]
in file preflight.py
self.set_header('Access-Control-Allow-Credentials', True)
should be replaced with
self.set_header('Access-Control-Allow-Credentials', 'true')

Because boolean True serialized as 'True' and will not accepted by browser. 
Tested in firefox and chrome.
It should be in lowercase.
When I replaced boolean true with string value it works fine.

**Comment by mrjoes** [comment]
Already fixed by https://github.com/MrJoes/tornadio2/commit/4d18fd94820ecc3df25cb935e758661fdfccbe7f
