### ISSUE TITLE
SocketConnection,on_open(),get_cookie(),always returns None.

### ISSUE THREAD

**Issue by 2469612734** [mrjoes/tornadio2#40]
Hi,
when I uses get_cookie() on the "on_open()" method,it always returns None although I have set the cookie.Could you help me?
Thank you very much!

**Comment by thorlarholm** [comment]
I am guessing you are running a multiplexed setup with several endpoints.

You should read your cookies from the router connection, not the individual endpoint connections.

The [multiplexed](https://github.com/mrjoes/tornadio2/tree/master/examples/multiplexed) example demonstrates how to setup a router with multiple endpoints, in [multiplexed.py](https://github.com/mrjoes/tornadio2/blob/master/examples/multiplexed/multiplexed.py).

**Comment by 2469612734** [comment]
Thank you very much,thorlarholm.
Your solution is right.I have solved the problem.The problem is on the endpoints.

**Comment by mrjoes** [comment]
Nice one, thank you for response :-)
