### ISSUE TITLE
Support engine.io

### ISSUE THREAD

**Issue by fawzyj** [mrjoes/tornadio2#47]
Socket.io 1.0 is around the corner , with its new core transport component engine.io (which also can be used standalone) , and actually many developers are shifting to use engine.io , because it is lightweight and more scalable than the full stack socket.io

I think that  natively supporting engine.io is essential feature

**Comment by mrjoes** [comment]
Sorry, I'm closing for now. Engine.io is not stable yet (and almost a year has passed), so if I manage to add engine.io support, it will be separate project.
