### ISSUE TITLE
None of the examples work

### ISSUE THREAD

**Issue by aroman** [mrjoes/tornadio2#5]
when starting any of the example servers, this occurs:

tornadio2/examples/transports >>> python transports.py 
INFO:root:Starting up tornadio server on port '8001'
Traceback (most recent call last):
  File "transports.py", line 55, in <module>
    tornadio2.server.SocketServer(application)
  File "/usr/lib64/python2.6/site-packages/TornadIO2-0.0.1-py2.6.egg/tornadio2/server.py", line 58, in **init**
    self.listen(socket_io_port, socket_io_address)
  File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 100, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 265, in bind_sockets
    sock.bind(sockaddr)
  File "<string>", line 1, in bind
socket.error: getsockaddrarg: bad family
tornadio2/examples/transports >>> python --version
Python 2.6.7
tornadio2/examples/transports >>> 

---

Cloned from git today, Tornado version 2.1.1

---

EDIT: Upon further investiagtion, the issue seems to be that session.py (specifically line 65) seems to think that tornado.httpserver.HTTPRequest has a 'cookies' attribute. It doesn't :P

**Comment by mrjoes** [comment]
Looks like you're having problem with IPv6 support in your Python version.
Someone else had similar problem with tornado itself:
https://groups.google.com/group/python-tornado/browse_thread/thread/3ec04536e57a2833

So, you if pass socket_io_address='0.0.0.0' setting to the application (basically, force
IPv4) and it should work as expected.

Hope it helps.
