### ISSUE TITLE
TornadIO2 should allow the user to override message type (Message of Json)

### ISSUE THREAD

**Issue by kiddouk** [mrjoes/tornadio2#50]
TornadIO2 now chooses the type of message to be sent according to the type of the data. `string` generates simple messages (type 3) while `dict` and `arrays` generate JSON messages (type 4). This is generally true except when the `string` already represent the JSON encoded   version of the object.

TornadIO2 should allow the user to override this behavior.

**Comment by mrjoes** [comment]
Patches are always welcome :-)
