### ISSUE TITLE
Room support

### ISSUE THREAD

**Issue by adambratt** [mrjoes/tornadio2#57]
Are there any plans for adding room support into tornadio2?

https://github.com/LearnBoost/socket.io/wiki/Rooms

**Comment by mrjoes** [comment]
Nope, rooms won't be added to the Tornadio2.

Rationale: rooms is abstraction which gathers users. And it is quite limited abstraction - you application might want to group users in different fashion and you won't be able to use built-in rooms anymore.

Plus, it is so easy to implement rooms by yourself. Naive implementation is dictionary where key is room name and value is list of connection objects. When you want to send something to the room, you do `self.broadcast(rooms['name')`.
