### ISSUE TITLE
PyPi

### ISSUE THREAD

**Issue by suquant** [mrjoes/tornadio2#58]
Please upgrade PyPi repositories for package "tornadio2"

When i install "pip install tornadio2" that installed old version package without some fixed bugs :(
its very discomfortable, also when i install from github repositories from master 
"-e git+git://github.com/mrjoes/tornadio2/#egg=TornadIO2" its not working correctly, because  TornadIO2-0.0.3-py2.7.egg-info has incorrect link to source for examle that included "../tornadio2/" 
but source installed in venv/src/tornadio2/tornadio2/... 

Do you know why pip do that? It is correctly behavior for pip ?

**Comment by scragg0x** [comment]
Hmm, I installed with pip and got the same version number as the github repo.  Are they different?

**Comment by mrjoes** [comment]
I will release new package tomorrow. While github version contains some fixes (nothing critical though), version was not bumped.

**Comment by suquant** [comment]
In master included critical bugfix, that "Do not Cookie check for Access-Control-Allow-Credentials" for us its critical.

Thanks.

**Comment by scragg0x** [comment]
Thanks @soloweb for pointing that out, I guessing I'm using at least a 7month old version.  @mrjoes bump it :+1:

**Comment by suquant** [comment]
Not for that :)

Also in old version do not correctly work "ACK" functions !!!
In my opinion its very critical bug and its seems actually version work correctly :)

**Comment by mrjoes** [comment]
This was completed.
