### ISSUE TITLE
Tornadio and AppEngine

### ISSUE THREAD

**Issue by emiltem** [mrjoes/tornadio2#62]
if running on Windows:

tornadio2\router.py in ()
     22 """
     23 
=>   24 from tornado import ioloop, version_info

//////////////////////////////////////////////////////////////
\tornado\ioloop.py in ()
     47     signal = None
     48 
=>   49 from tornado.platform.auto import set_close_exec, Waker

//////////////////////////////////////////////////////////////
tornado\platform\auto.py in ()
     30 if os.name == 'nt':
     31     from tornado.platform.common import Waker
=>   32     from tornado.platform.windows import set_close_exec

//////////////////////////////////////////////////////////////
tornado\platform\windows.py in ()
      4 
      5 from **future** import absolute_import, division, with_statement
=>    6 import ctypes

//////////////////////////////////////////////////////////////
-- \Python27\lib\ctypes__init__.py in ()
      8 **version** = "1.1.0"
      9 
=>   10 from _ctypes import Union, Structure, Array
/////////////////////////////////////////////////////////////
<type 'exceptions.ImportError'>: No module named _ctypes 
      args = ('No module named _ctypes',) 
      message = 'No module named _ctypes'

if deploy:
Error: Server Error

**Comment by mrjoes** [comment]
Tornado does not run very well on Windows - it uses select() instead of epoll/kqueue, so try avoid using Windows.
