### ISSUE TITLE
THANK YOU SO MUCH FOR WORKING WHEN PLAIN WEBSOCKETS TORNADO EXAMPLE DID NOT WORK!!

### ISSUE THREAD

**Issue by DTrejo** [mrjoes/tornadio2#63]
YOU ARE THE BEST THANK YOU FOR YOUR CODE AND SERVICE TO HUMANITY EVERYWHERE.

Hugs,
D

**Comment by mrjoes** [comment]
Err, if you really need websocket replacement, check different project - https://github.com/mrjoes/sockjs-tornado
