### ISSUE TITLE
Running TornadIO2 with Tornado using Supervisord and different ports throws "socket.error: [Errno 98] Address already in use"

### ISSUE THREAD

**Issue by lonelycode** [mrjoes/tornadio2#67]
I'm writing a Tornado app and one of the aspects of it is that it provides real-time updates to the client via SocketIO.

The Tornado documentation suggests using Supervisor to run multiple processes of Tornado (one per core) behind NginX.

I've set it up so that the Tornado and TornadIO applications bind to different ports for each process, when the server starts up. However it looks like the TornadIO2 implementation can't bind to '0.0.0.0' more than once?

Maybe I'm doing something wrong - I'm setting the variables in the applications settings as such:

project_settings = {
    "debug": True,
    "xheaders": True,
    "socket_io_port": 8081,
    "socket_io_address": "0.0.0.0"
}

When unsetting the socketio_address field it still raises the same error.

Thanks,
Martin

**Comment by mrjoes** [comment]
Are you sure you're changing socket_io_port configuration value for each instance?
